Update ConfigCollector.yml

diff --git a/.github/workflows/ConfigCollector.yml b/.github/workflows/ConfigCollector.yml
--- a/.github/workflows/ConfigCollector.yml
+++ b/.github/workflows/ConfigCollector.yml
@@ -18,7 +18,8 @@ jobs:
     - name: Set up Go
       uses: actions/setup-go@v5
       with:
-        go-version: '1.17'
+        go-version: '1.19'
+        go-mod-path: Files/go.mod
     - name: Install Go dependencies
       working-directory: ./Files
       run: go mod download
@@ -56,9 +57,11 @@ jobs:
       run: |
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
-        git pull origin main --rebase
-        git add ./bulk/*
-        git checkout main
+        git status
+        git add . || echo "No files to add"
+        git commit -m "Stage changes before pull" || echo "No changes to commit"
+        git pull origin main --rebase || echo "Pull failed, continuing"
+        git add . || echo "No files to add"
         git commit -m "☠️ $(date '+%Y-%m-%d %H:%M:%S') Collected" || echo "No changes to commit"
     - name: Push Changes
       uses: ad-m/github-push-action@v0.8.0
