Update ConfigCollector.yml

diff --git a/.github/workflows/ConfigCollector.yml b/.github/workflows/ConfigCollector.yml
--- a/.github/workflows/ConfigCollector.yml
+++ b/.github/workflows/ConfigCollector.yml
@@ -9,22 +9,31 @@ jobs:
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
+    - name: Set up PHP
+      uses: shivammathur/setup-php@v2
+      with:
+        php-version: '8.0'
+    - name: Run PHP processor
+      run: php Files/vmess_processor.php > php_run.log 2>&1
     - name: Set up Go
       uses: actions/setup-go@v5
       with:
         go-version: '1.17'
     - name: Install Go dependencies
+      working-directory: ./Files
       run: go mod download
     - name: Build and run Golang file
+      working-directory: ./Files
       run: go run ./main.go > go_run.log 2>&1
     - name: Move Files to Bulk Directory
       run: |
         mkdir -p bulk
-        mv vmess_iran.txt bulk/ || echo "vmess_iran.txt not found"
-        mv trojan_iran.txt bulk/ || echo "trojan_iran.txt not found"
-        mv vless_iran.txt bulk/ || echo "vless_iran.txt not found"
-        mv ss_iran.txt bulk/ || echo "ss_iran.txt not found"
-        mv mixed_iran.txt bulk/ || echo "mixed_iran.txt not found"
+        mv Files/vmess_iran.txt bulk/ || echo "vmess_iran.txt not found"
+        mv Files/trojan_iran.txt bulk/ || echo "trojan_iran.txt not found"
+        mv Files/vless_iran.txt bulk/ || echo "vless_iran.txt not found"
+        mv Files/ss_iran.txt bulk/ || echo "ss_iran.txt not found"
+        mv Files/mixed_iran.txt bulk/ || echo "mixed_iran.txt not found"
+        mv Files/vmessclean.txt bulk/ || echo "vmessclean.txt not found"
     - name: Create merge1.txt
       run: |
         cat ./bulk/ss_iran.txt ./bulk/trojan_iran.txt > ./bulk/merge1.txt || echo "Failed to create merge1.txt"
@@ -50,7 +59,7 @@ jobs:
         git pull origin main --rebase
         git add ./bulk/*
         git checkout main
-        git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected" || echo "No changes to commit"
+        git commit -m "☠️ $(date '+%Y-%m-%d %H:%M:%S') Collected" || echo "No changes to commit"
     - name: Push Changes
       uses: ad-m/github-push-action@v0.8.0
       with:
