Update speedTEST.yml

diff --git a/.github/workflows/speedTEST.yml b/.github/workflows/speedTEST.yml
--- a/.github/workflows/speedTEST.yml
+++ b/.github/workflows/speedTEST.yml
@@ -14,7 +14,7 @@ jobs:
         with:
           php-version: '8.0'
       - name: Run PHP processor
-        run: php Files/vmess_processor.php > php_run.log 2>&1
+        run: php Files/vmess_processor.php > logs/php_run.log 2>&1
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
@@ -26,16 +26,16 @@ jobs:
       - name: Install Requirements
         run: |
           pip install speedtest-cli
-          pip install -r ./utils/requirements.txt > pip_install.log 2>&1
+          pip install -r ./utils/requirements.txt > logs/pip_install.log 2>&1
       - name: Create output directories
-        run: mkdir -p ./sub/splitted
+        run: mkdir -p ./sub/splitted ./utils/speedtest
       - name: Check input files
         run: |
           ls -l ./bulk/merge1.txt ./bulk/merge2.txt ./bulk/merge3.txt ./bulk/vmessclean.txt || echo "Input files not found"
       - name: Run Lite Speedtest
         run: |
-          sh ./utils/speedtest/speedtest2.sh > speedtest.log 2>&1
-          ls -l ./out.json || echo "out.json not found"
+          sh ./utils/speedtest/speedtest2.sh > logs/speedtest.log 2>&1
+          ls -l ./utils/speedtest/out.json || echo "out.json not found"
           python ./utils/speedtest/output.py
       - name: Commit Changes
         run: |
@@ -46,7 +46,7 @@ jobs:
           git commit -m "Stage changes before pull" || echo "No changes to commit"
           git pull origin main --rebase || echo "Pull failed, continuing"
           git add Allconfig Base64.txt V2.txt ./sub/sub_merge.txt ./sub/sub_merge_base64.txt LogInfo.txt ./sub/splitted/* ./bulk/* || echo "No files to add"
-          git commit -m "☠️ $(date '+%Y-%m-%d %H:%M:%S') Speed Test" || echo "No changes to commit"
+          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Speed Test" || echo "No changes to commit"
       - name: Push Changes
         uses: ad-m/github-push-action@v0.8.0
         with:
